### ISSUE TITLE
Could not run the experiment. Need the correct FeatureEngineering.py. No test features computed. 

### ISSUE THREAD

**Issue by nhianK** [Zhaoxing-Li/MLFBK#2]

**Comment by nhianK** [comment]
I was able to run the IKT handler and produce ikt feature test, train and validation files. However, still unable to run the code. Got error message: 
2024-04-22 23:17:18.906039: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-22 23:17:19.383093: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
COLUMNS Index(['10, 540397', '14, 618628', '537, 362118'], dtype='object')
Traceback (most recent call last):
  File "/home/anikanahian/miniconda3/envs/priv-bert/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main(config)
  File "main.py", line 18, in main
    train_loader, valid_loader, test_loader, num_q, num_r, num_pid, num_diff, num_ap, num_pd, num_sm = get_loaders(config)
  File "/media/anikanahian/OS/code-exp/KT/knowledge-tracing-bert-transformers/MLFBK/src/get_modules/get_loaders.py", line 17, in get_loaders
    train_dataset, test_dataset, valid_dataset, fe = EDNET_PID_SPLIT(config.max_seq_len)
  File "/media/anikanahian/OS/code-exp/KT/knowledge-tracing-bert-transformers/MLFBK/src/Dataloaders/ednet_pid_loader.py", line 253, in EDNET_PID_SPLIT
    fe = FeatureEnumerator()
  File "/media/anikanahian/OS/code-exp/KT/knowledge-tracing-bert-transformers/MLFBK/src/Dataloaders/ednet_pid_loader.py", line 25, in __init__
    self.u_list = np.unique(df["user_id"].values)
  File "/home/anikanahian/miniconda3/envs/priv-bert/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/anikanahian/miniconda3/envs/priv-bert/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'user_id'



The csv files do not have the columns specified. Could you help me reproduce these files by uploading the updated version of your code?
